#!/bin/bash

#GET TIME, THEN FOR X TIMES GET THE UNIX EPOCH VALUE AND ENCRYPT IT IN DIFFERENT FORMATS, THEN GET ALL THE STRINGS AND LOWERCASE THEM.
#THEN CHOOSE A PIECE FROM ALL OF THEM AND PUT THEM TOGHETHER, RANDOMLY CAPITALIZING IT AND ADD RANDOM SYMBOLS INTO THE MIX.
#OH, AND ALSO, SHORTEN THE FINAL RESULT TO 16 CHARS.


echo "Bash version ${BASH_VERSION}..."
#set date
CURRENTDATE='date'
CURRENTDATEUNIXEPOCH='date +%s'
SPECIALCHARS='!@#$%^&*()_+'
#do "x" 12 times
for i in {1..12} do (
date +%s | sha128sum | base64 | head -c 32
RANDOMCHAR=${SPECIALCHARS:RANDOM % ${#SPECIALCHARS}:1}
RANDOMPOS=$(( RANDOM % ( ${#BANK} + 1 ) ))
BANK_NEW=${BANK:0:RANDOMPOS}${RANDOMCHAR}${BANK:RANDOMPOS}
)


